### ISSUE TITLE
Efficacy boundary in the t scale

### ISSUE THREAD

**Issue by pdeninis** [cran/rpact#1]
First, I would like to congratulate you on your outstanding work!

It is really a godsend! Besides being valuable for its specific usage of aid in the design of studies, I believe it has a just as important educational value too, allowing to easily acquire a deeper depiction of the phenomenon.

I appreciate the noticeable supporting documentation, which is a pivotal tool for its proper usage.

I suspect it will take a while to understand thoroughly, but surely it is worthwhile. 

Now, my question. 
I guess according to the custom of the literature about groups sequential trials, the Efficacy boundary is reported in the z scale.
However, a checkbox is available to choose whether applying the "normal approximation". In the [step-by-step tutorial, point 5](https://www.rpact.com/vignettes/rpact_step-by-step_tutorial#5_Power_analysis_for_group_sequential_designs), it is explained that :

> the default settings where the calculations are based on the t distribution, will be (ever so slightly) more accurate.

Not knowing the logic of the package, I suppose that the checkbox is influential in calculating the sample-size, as it gets slightly smaller whenever it is flagged. However, still being reported in the z scale, the Efficacy boundary is unaffected by it. 

I was wondering whether there is a proper usage for the Efficacy boundary in z scale when the outcome is continuous so its critical value is reported as a t-value. It would be not the proper threshold, so it would be preferable to have it in the t scale.

Since a _local significance level_ is even shown, I had hypothesized to use it to calculate the Efficacy boundary in the t scale, e.g.:

```
> df<-ceiling(getSampleSizeMeans(design, alternative = 0.3, stDev = 0.5, groups = 1)$numberOfSubjects)
     [,1]
[1,]   22
[2,]   44

> qt(pnorm(design$criticalValues[1]),df)
         [,1]
[1,] 2.329901
[2,] 2.251673
```

Some time later, I noted this image at the bottom showing that G*Power did report it.
 
![image](https://user-images.githubusercontent.com/35506062/174066662-92cdb0a8-115b-4f64-864e-286aacbe0217.png)

So I would like to know whether you agree in presenting it (if there is no contraindication) and whether it might be added in a future update.

Thank you!
Paolo

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by pdeninis** [comment]
Sorry, I didn't see it.
