### ISSUE TITLE
How to get AIC from piecewise exponential

### ISSUE THREAD

**Issue by vinwol** [cran/rpact#2]
With PWEXP, I think you can do: 
fit <- pwexp.fit(...)
fit$AIC
How can you get the AIC for getPiecewiseExponentialDistribution(...)?

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!
